
export default {
  ORG_SEARCH: 'ORG_SEARCH',
  ORG_RELOAD: 'ORG_RELOAD',
  ORG_SAVE: 'ORG_SAVE',
  ORG_EDIT: 'ORG_EDIT',
  ORG_EDIT_CANCEL: 'ORG_EDIT_CANCEL',
  ORG_DELETE: 'ORG_DELETE',
  REMOVE_LISTENER:'REMOVE_LISTENER',
  ADD_LISTENER:'ADD_LISTENER'
};
